### ISSUE TITLE
Object Detection Using Computer Vision

### ISSUE THREAD

**Issue by jeffryjames** [prathimacode-hub/DS-ScriptsNook#9]
**Object detection**  is related to computer vision and image processing that deals with detecting instances of semantic objects of a certain class (such as humans, buildings, or cars) in digital images and videos. Given an image or a video stream, an object detection model can identify which of a known set of objects might be present

![download](https://user-images.githubusercontent.com/43547815/125199798-95ff5b00-e285-11eb-8891-fa861dd47263.jpg)

**Comment by shivani6320** [comment]
Hey @prathimacode-hub  ! I would like to work on this issue. I will use RCNN for the object detection in images. Please assign me this issue as DevIncept Participant.

**Comment by prathimacode-hub** [comment]
@shivani6320, as issues are assigned on first come first serve basis, jeffry would be eligible to take this up first. If he doesn't respond, then you would be considered. 

@jeffryjames Kindly follow the issue template given to get issues assigned. And are you a participant of LGMSOC, Devincept or Contributor. How would I know what you are, if you don't follow the template. And also, hope you had read the README and CONTRIBUTING GUIDELINES of the project. Also let me know of task you will be working on "Algorithm" or "Tutorial". Please provide these details while raising an issue, so that it would be easier for us to assign the issues. @jeffryjames

**Comment by jeffryjames** [comment]
> @shivani6320, as issues are assigned on first come first serve basis, jeffry would be eligible to take this up first. If he doesn't respond, then you would be considered.
> 
> @jeffryjames Kindly follow the issue template given to get issues assigned. And are you a participant of LGMSOC, Devincept or Contributor. How would I know what you are, if you don't follow the template. And also, hope you had read the README and CONTRIBUTING GUIDELINES of the project. Also let me know of task you will be working on "Algorithm" or "Tutorial". Please provide these details while raising an issue, so that it would be easier for us to assign the issues. @jeffryjames

@prathimacode-hub  I have Created Another issue and working on it. Let this issue be assigned to @shivani6320 .  Thank you!

**Comment by prathimacode-hub** [comment]
On request of @jeffryjames. this issue is assigned to you. Hope you are willing to. @shivani6320

**Comment by shivani6320** [comment]
ok @prathimacode-hub ! Noted. I'll work towards it.
